os: linux
dist: bionic

language: node_js
node_js:
  - 'node'
  - 'lts/*'

cache:
  npm: true

install:
  - npm i

script:
  - npm run lint
  - npm run build

deploy:
  - provider: pages:git
    edge: true
    verbose: true
    on:
      node_js: node

