os: linux
dist: bionic

language: node_js
node_js:
  - 'node'
  - 'lts/*'

cache:
  npm: true

install:
  - npm install

script:
  - npm run lint
  - npm run build

deploy:
  provider: pages
  edge: true
  verbose: true
  cleanup: false
  local_dir: ./dist
  on:
    node_js: node
